plpdjango/ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'ecommerce'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.product_list, name='product_list'),  
    path('products/<int:pk>/',views.product_detail, name='product_detail'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/<int:pk>', views.customer_detail, name='customer_detail'),
]

plpdjango/plpdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerce/', include('ecommerce.urls')),
]

plpdjango/ecommerce/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    price = models.DecimalField(max_digits=10,decimal_places=2)
    image = models.ImageField(upload_to='products/')
    availability = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class Customer(models.Model):
    First_name = models.CharField(max_length=20)
    Last_name = models.CharField(max_length=20)
    Email = models.EmailField(unique=True)
    Phone_number = models.CharField(max_length=15, blank=True, null=True)
    Address = models.TextField(blank='True', null='True')

    def __str__(self):
        return f"{self.First_name}{self.Last_name}{self.Email}"

plpdjango/ecommerce/views.py
from django.shortcuts import get_object_or_404, render
from .models import Customer, Product


# Create your views here.
def product_list(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'ecommerce/product_list.html', context)

def product_detail(request, pk):
    product = get_object_or_404 (Product, pk=pk)
    context = {
        'product' : product
    }
    return render(request, 'ecommerce/product_detail.html', context)

def customer_list(request):
    customers = Customer.objects.all()
    context ={
        'customers': customers
    }
    return render(request, 'ecommerce/customer_list.html', context)

def customer_detail(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    context = {
        'customer' : customer
    }
    return render(request, 'ecommerce/customer_detail.html', context)

def home(request):
    return render(request, 'ecommerce/home.html')

plpdjango/ecommerce/templates/ecommerce/customer_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Details</title>
</head>
<body>
    <h1>Customer details</h1>
    <div class="container">
        <div class="customer-detail">
           <h3><strong>Name: </strong>{{customer.First_name}} {{customer.Last_name}}</h3> 
           <p><strong>Phone: </strong> {{customer.Phone_number}}</p>
           <p><strong>Email: </strong> {{customer.Email}}</p>
           <p><strong>Address: </strong> {{customer.Address}}</p>

        </div>
    </div>
    
</body>
</html>

plpdjango/ecommerce/templates/ecommerce/customer_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer_list</title>
</head>
<body>
    <h1>Customer list</h1>
    <ul>
        {% for customer in customers %}
        <li>
            <a href="{% url 'ecommerce:customer_detail' customer.pk %}">
                {{customer.First_name}}{{customer.Last_name}}{{customer.Email}}
            </a>
        </li>
        {% endfor %}
    </ul>
    
</body>
</html>

plpdjango/ecommerce/templates/ecommerce/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecommerce</title>
    <link rel="stylesheet"  href="{% static 'ecommerce/style.css %'}">
</head>
<body>
    <h1>Welcome to Our E-commerce Site</h1>
    <nav>
        <ul>
            <li><a href="{% url 'ecommerce:product_list' %}">Product List</a></li>
            <li><a href="{% url 'ecommerce:customer_list' %}">Customer List</a></li>
        </ul>
    </nav>
</body>
</html>

plpdjango/ecommerce/templates/ecommerce/product_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product detail</title>
</head>
<body>
    <h1><b>Products Detail</b></h1>
    <ul>
        {% for Product in products%}
        <li>
            <h2>{{Product.name}}</h2>
            <p> {{Product.description}}</p>
            <p>Price: Ugx. {{Product.price}}</p>
            <img src="{{Product.imge.url}}" alt="{{Product.name}}">
            <p>Available: {{product.available|yesno:"Yes,No"}}</p>
        </li>
        {% endfor %}
    </ul>
    
</body>
</html>

plpdjango/ecommerce/templates/ecommerce/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1><b>Products List</b></h1>
    <ul>
        {% for Product in products %}
        <li>
            <h2>{{Product.name}}</h2>
            <p> {{Product.description}}</p>
            <p>Price: Ugx.{{Product.price}}</p>
            <img src="{{Product.imge.url}}" alt="{{Product.name}}">
        </li>
        {% endfor %}
    </ul>
    
</body>
</html>